config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :products  do
    resources :comments
  end

resources :users do
    member do
      get :following, :followers
    end
  end
  resources :comments
resources :relationships,       only: [:create, :destroy]

  root :to => 'products#index'
  
  get 'cart' => 'cart#index' 
  get 'cart/clear' => 'cart#clearCart'
  get 'cart/:id' => 'cart#add'
  get 'thankyou' => 'thankyou#index'
  get 'thankyou/:id' => 'thankyou#download'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'products/show_categories'
  

end

app/models/user.rb
class User < ActiveRecord::Base
has_many :products, dependent: :destroy
has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
								  
 has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
								 
has_many :following, through: :active_relationships, source: :followed
has_many :followers, through: :passive_relationships, source: :follower
 

before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
has_attached_file :image
 validates_attachment :image, presence: true,
                     size: { in: 0..5000.kilobytes }
do_not_validate_attachment_file_type :image	


 # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

	 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in!, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]
  before_action :set_user, only: [:show]

  # GET /users
  # GET /users.json
  def index
  	if logged_in? 
		if !current_user.isAdmin
			redirect_to root_path
		end
	else
		redirect_to root_path
	end
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
	if current_user 
		if @user.id != current_user.id
			redirect_to root_path
		end
	else 
		redirect_to root_path
	end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
	
    respond_to do |format|
      if @user.save
	    log_in @user
        format.html { redirect_to @user, success: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, success: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, success: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end 
  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password,
                                   :password_confirmation, :image)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
 <%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
	 <div class="alert alert-danger">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
</div>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
  <%= f.label :image %><br>
    <%= f.file_field :image%>
</div>
  <br/>
  <div class="actions">
    <%= f.submit "Create Account", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<tr>
<td>
 <div class="row featurette">
	<div class="col-md-1">
		<%= link_to image_tag(user.image.url, class: 'media-object round-image-50'), :controller => "users", :action => "show", :id => user.id %>
	</div>
	<div class="col-md-4">
		<%= link_to user.username, user %>
	</div>
</div>
</td>
</tr>  

app/views/users/_user_info.html.erb
 <div class="row featurette"> 
		<%= image_tag(@user.image.url, class: 'media-object picture profilepic center-block')%>
		<br>
		<p>
		  <%= @user.email %>
		</p>
		
		<% @user ||= current_user %>
		<div class="stats">
			<div class="col-md-6">
				  <a href="<%= following_user_path(@user) %>">
				  Following:
					<strong id="following" class="stat">
					  <%= @user.following.count %>
					</strong>
				  </a>
			</div>
			<div class="col-md-6">
				  <a href="<%= followers_user_path(@user) %>">
				  Followers:
					<strong id="followers" class="stat">
					  <%= @user.followers.count %>
					</strong>
				  </a>
				  </div>
		</div>
		<br>
		<%= render 'follow_form' if logged_in? %>
		<br/>
		<% if current_user?(@user) %>
			<%= link_to 'Edit Account', edit_user_path(@user), :class => "btn" %> 
		<% end %>
	</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<% if logged_in? %>
		  <% if current_user.isAdmin %>
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
		<td><%= link_to image_tag(user.image.url, class: 'media-object picture'), user %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user), :class => "btn" %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<% end %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-2 text-center">
       <%= render 'user_info' %>
    </aside>
  <div class="col-md-8">
            <div class="container">
                <div class="row featurette">
                    <div class="col-md-12">
						<h3>User's Music</h3>
						<% if @user.products.blank? %>
						<p>There is currently no music uploaded by this user.</p>
						<% else %>
						<table class="table table-bordered">
						<% @user.products.each do |product| %>
						<tr>
						<td><div class="row featurette">
							<div class="col-md-4">
								<%= link_to image_tag(product.image.url, class: 'media-object picture'), product %>
							</div>
							<div class="col-md-8">
								<h2><%= link_to product.name, product %></h2>
								<p><%= product.description %></p>
								<% if current_user?(@user) %>
									<%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn" %>
								<% end %>
							</div>
						</div></td>
						</tr>
						<% end %>
						</table>
						<% end %>
                    </div>
                </div>
            </div>
        </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-2 text-center">
    <%= render 'user_info' %>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <table class="table table-bordered">
        <%= render @users %>
      </table>
    <% end %>
  </div>
</div>