config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :products  do
    resources :comments
  end

resources :users do
    member do
      get :following, :followers
    end
  end
  resources :comments
resources :relationships,       only: [:create, :destroy]

  root :to => 'products#index'
  
  get 'cart' => 'cart#index' 
  get 'cart/clear' => 'cart#clearCart'
  get 'cart/:id' => 'cart#add'
  get 'thankyou' => 'thankyou#index'
  get 'thankyou/:id' => 'thankyou#download'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'products/show_categories'
  

end

app/models/product.rb
class Product < ActiveRecord::Base
   belongs_to :category
   belongs_to :user
   has_many :comments, dependent: :destroy
   validates_presence_of :name

has_attached_file :image
validates_attachment :image, presence: true,
                     size: { in: 0..10000.kilobytes }
do_not_validate_attachment_file_type :image	

has_attached_file :audio  ,
                    :url => "/assets/:class/:id/:attachment/:style.:extension",
                    :path => ":rails_root/public/assets/:class/:id/:attachment/:style.:extension"

validates_attachment_content_type :audio, :content_type => [ 'audio/mpeg', 'audio/m4a', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio' ]

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
	@product = Product.find(params[:id])
  end

  
  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
	@user_id = session[:user_id]
  end

  # GET /products/1/edit
  def edit
	if current_user 
		if @product.user_id != current_user.id
			redirect_to root_path
		end
	else 
		redirect_to root_path
	end
  
	@product = Product.find(params[:id])
     @categories = Category.all
  end

  def show_categories
      @category = Category.find(params[:id])
   end
  
  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
	@categories = Category.all
	@product.user_id = current_user.id if current_user
	
	ShopifyAPI::Base.site = "https://3cc4777fa0a4e64622d58af9ae8c8edf:dfb10343edec3c735e3be99fb6df2f15@tuneify-2.myshopify.com/admin"

    new_product = ShopifyAPI::Product.new
	new_product.title = @product.name
	new_product.body_html = @product.description
	new_product.product_type = "Song"
	new_product.vendor = "Tuneify"
	new_product.variants = ShopifyAPI::Variant.new	
	new_product.save
	
	variant = ShopifyAPI::Variant.find(new_product.variants[0].id)	
	variant.price = @product.price
	variant.requires_shipping = false
	variant.save
	
	@product.shopify_id = new_product.variants[0].id
	
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, success: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
  @categories = Category.all
  
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, success: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
	@user = current_user
    @product.destroy
    respond_to do |format|
      format.html { redirect_to @user, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :category_id, :image, :audio, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
	  
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
   <label for = "category_id">Category</label>:
   <%= collection_select(:product, :category_id, @categories, :id, :name, prompt: true) %>
  </div>
  <div class="field">
  <%= f.label :image %><br>
    <%= f.file_field :image%>
</div>
<div class="field">
  <%= f.label :audio %><br>
    <%= f.file_field :audio%>
</div>
  <br>
  <div class="actions">
    <%= f.submit "Create Product", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/products/edit.html.erb
<h4><%= link_to '< Back', products_path %></h4>
<h1>Editing Product</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<h1>All Music:</h1>
<% if @products.blank? %>
<p>There is currently no music in the system right now.</p>
<% else %>
<table class="table table-bordered">
<% @products.each do |product| %>
  <tr><div class="row featurette">
<td><div class="col-md-4">
		<%= link_to image_tag(product.image.url, class: 'media-object picture'), product %>
	</div>
	<div class="col-md-8">
		<h2><%= link_to product.name, product %></h2>
		<p><%= product.description %></p>
	</div></td>
</div></tr>
<% end %>
</table>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

 <div class="row featurette">
            <div class="col-md-4">
                <%=  image_tag(@product.image.url, class: 'media-object display_picture') %>
            </div>
            <div class="col-md-8">	
			<div class="row" >
				<div class="col-md-2">
					<%= link_to image_tag("play.png", class: 'media-object'), @product.audio.url, :class => "play_song", remote:true%>				
				</div>
				<div class="col-md-8">					
					<h1>
					  <%= @product.name %> 
					  <% if current_user %>
					<% if @product.user_id == current_user.id %>
					<%= link_to 'Edit', edit_product_path(@product), :class => "btn"  %>
					<% end %>
					<%end %>
					</h1>
					<% user = User.find(@product.user_id) %>
					<h3>  <%= link_to user.username, :controller => "users", :action => "show", :id => user.id %> </h3>
				</div>
			</div>
				<br>
				<div class="row">
		<p>
		  <%= link_to @product.category.name, :controller => "categories", :action => "show", :id => @product.category.id %>
		</p>
		<p>
		  <%= @product.description %>
		  <br>
		  <h3>$<%= @product.price %></h3>
		  <br>
		  <%= button_to "Add to cart", {:controller => "cart", :action => "add", :id => @product.id }, :method => "get", :class => "btn"  %>
		</p>
</div>
</div>
</div>

<br>
<br>
<div class="row featurette">
		<% if current_user %>

		<%= form_for [@product, Comment.new]	do |f| %>
		<p>
			<strong>Post a Comment:</strong><br>
			<%= f.text_area :text, :label => "New Comment" %> 
		</p>
		<p><%= f.submit "Add Comment", class: "btn btn-primary", remote:true %></p>
		<% end %>
		<% end %>
		<br>
		<% if @product.comments.count == 1 %>
			<H4><%= @product.comments.count %> Comment:</H4>
		<% else %>
			<H4><%= @product.comments.count %> Comments:</H4>
		<% end %>
		
		<% if @product.comments.blank? %>
			<p> There are currently no comments.</p>
		<% else %>		
		<div id="comments">
			<table class="table table-bordered">
			<%= render :partial => @product.comments %>
			</table>
		</div>		
		<% end %>
		
</div>

app/views/products/show_categories.html.erb
<h1><%= @category.name -%></h1>

<ul>
   <% @category.products.each do |c| %>
   <li><%= link_to c.name, :action => "show", :id => c.id -%></li>

   <% end %>
</ul>