config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :products  do
    resources :comments
  end

resources :users do
    member do
      get :following, :followers
    end
  end
  resources :comments
resources :relationships,       only: [:create, :destroy]

  root :to => 'products#index'
  
  get 'cart' => 'cart#index' 
  get 'cart/clear' => 'cart#clearCart'
  get 'cart/:id' => 'cart#add'
  get 'thankyou' => 'thankyou#index'
  get 'thankyou/:id' => 'thankyou#download'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'products/show_categories'
  

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
	  <%= link_to image_tag("tuneify_logo.png"), root_path, :class => "navbar-brand logo" %>
	  <%= link_to "Tuneify", root_path, :class => "navbar-brand"%>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul id = "categories" class="nav navbar-nav">
			<% Category.all.each do |c| %>
			<li><%= link_to c.name, :controller => "categories", :action => "show", :id => c.id %></li>
			<% end %>
		</ul>
		
		<ul class="nav navbar-nav navbar-right">
		<% if logged_in? %>
		  <% if current_user.isAdmin %>
		  <li><%= link_to 'Admin', categories_path %></li>
		  <% end %>
		  <li><%= link_to 'Cart', cart_path %></li>
		  <li><%= link_to 'Upload', new_product_path %></li>
		  <li class="round-image-50"><%= image_tag(current_user.image.url) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
		</ul>
    </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/_player.html.erb
<footer id="player" class="footer">
<div id="jquery_jplayer_1" class="jp-jplayer"></div>
<div id="jp_container_1" class="jp-audio" role="application" aria-label="media player" style="border:none; width: 100%; padding-left: 35%;">
  <div class="jp-type-single">
    <div class="jp-gui jp-interface">
      <div class="jp-controls">
        <button class="jp-play" role="button" tabindex="0">play</button>
		<button class="jp-pause" role="button" tabindex="0">pause</button>
        <button class="jp-stop" role="button" tabindex="0">stop</button>
      </div>
      <div class="jp-progress">
        <div class="jp-seek-bar">
          <div class="jp-play-bar"></div>
        </div>
      </div>
      <div class="jp-volume-controls">
        <button class="jp-mute" role="button" tabindex="0">mute</button>
        <button class="jp-volume-max" role="button" tabindex="0">max volume</button>
        <div class="jp-volume-bar">
          <div class="jp-volume-bar-value"></div>
        </div>
      </div>
      <div class="jp-time-holder">
        <div class="jp-current-time" role="timer" aria-label="time">&nbsp;</div>
        <div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
        <div class="jp-toggles">
          <button class="jp-repeat" role="button" tabindex="0">repeat</button>
        </div>
      </div>
    </div>
    <div class="jp-no-solution">
      <span>Update Required</span>
      To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
    </div>
  </div>
</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tuneify</title>
    <link href='https://fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "jplayer" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<div id="menu">
	<%= render :partial =>'layouts/navbar' %>
</div>
<div id="player">
	<%= render :partial =>'layouts/player' %>
</div>
<div id="content" class="container-fluid">
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
	<%= yield %>
</div>



</body>
</html>